---
- name: Metricbeat playbook
  hosts: webservers
  become: true
  tasks:
  - name: download metricbeat
    apt:
       deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
       state: present
  - name: copy metricbeat config file
    ansible.builtin.copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Run metricbeat mudules enable docker
    command: metricbeat modules enable docker
  - name: Run metricbeat setup
    command: metricbeat setup
  - name: Run service metricbeat start
    command: service metricbeat start

  - name: enable metricbeat
    systemd:
      name: metricbeat
      state: started
      enabled: yes
